variables:
  KUBERNETES_CPU_REQUEST: 2
  KUBERNETES_MEMORY_REQUEST: 4Gi
  KUBERNETES_EPHEMERAL_STORAGE_REQUEST: 5Gi

build:
  stage: build
  only:
    - master
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${GCP_AR}\":{\"auth\":\"$(printf "%s:%s" "_json_key" "${GCP_AR_KEY}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${GCP_AR_REPO}/manager-api:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}-$(date +%s)"
      --destination "${GCP_AR_REPO}/manager-api:edge"

release:
  stage: build
  only:
    - tags
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${GCP_AR}\":{\"auth\":\"$(printf "%s:%s" "_json_key" "${GCP_AR_KEY}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${GCP_AR_REPO}/manager-api:${CI_COMMIT_TAG}"
      --destination "${GCP_AR_REPO}/manager-api:latest"
